In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [4]:
np.array([1,2,3,4,5,'Hamid',4+9j])

array(['1', '2', '3', '4', '5', 'Hamid', '(4+9j)'], dtype='<U64')

In [5]:
type(np.array([1,2,3,4,5,'Hamid',4+9j]))

numpy.ndarray

In [6]:
np.array([1,2,3,4,4.5,6.0])

array([1. , 2. , 3. , 4. , 4.5, 6. ])

In [7]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [8]:
np.array([[1,3],[3,4],[6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [9]:
np.array([[1,3],[3,4],[6,7,8]])

<ipython-input-9-2fc331c0f648>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,4],[6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [10]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [11]:
np.array([1,2,3], ndmin=3)

array([[[1, 2, 3]]])

In [12]:
np.array([1,2,3],dtype=complex )

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

In [14]:
arr=np.array([(1,2),(3,4)], dtype=[('a','<i2'),('b','<i8')])

In [15]:
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [16]:
type(arr[0][0])

numpy.int16

In [17]:
type(arr[0][1])

numpy.int64

In [18]:
arr=np.array([(1,2),(3,4)], dtype=[('a','<i4'),('b','<i8')])

In [19]:
type(arr[0][0])

numpy.int32

In [20]:
type(arr[0][1])

numpy.int64

In [21]:
arr=np.array([[1,3],[3,4]])

In [22]:
arr

array([[1, 3],
       [3, 4]])

In [23]:
arr[0]

array([1, 3])

In [24]:
arr[0][1]

3

In [25]:
np.mat(arr)

matrix([[1, 3],
        [3, 4]])

In [26]:
mat=np.matrix(arr)
mat

matrix([[1, 3],
        [3, 4]])

In [27]:
l=[3,4,5,6,7]

In [28]:
np.array(l)

array([3, 4, 5, 6, 7])

In [29]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [30]:
np.asanyarray(l) #if data is already availabe in anykind of array it will not convert

array([3, 4, 5, 6, 7])

In [31]:
np.asarray(mat)

array([[1, 3],
       [3, 4]])

In [32]:
# matrix sub class hy ya nahi nd array ka
issubclass(np.matrix,np.ndarray)

True

In [33]:
issubclass(np.ndarray,np.matrix)

False

In [34]:
a=arr

In [35]:
b=np.copy(arr)   #deep copy and  solo copy

In [36]:
arr[0][0]=67
arr

array([[67,  3],
       [ 3,  4]])

In [37]:
a

array([[67,  3],
       [ 3,  4]])

In [38]:
b

array([[1, 3],
       [3, 4]])

In [39]:
arr[0:10]

array([[67,  3],
       [ 3,  4]])

In [40]:
arr[-1]

array([3, 4])

In [41]:
np.fromfunction(lambda i , j : i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [42]:
np.fromfunction(lambda i , j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [43]:
np.fromfunction(lambda i , j : i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [44]:
np.fromfunction(lambda i , j : i/j,(3,3))

<ipython-input-44-231d4427c425>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i , j : i/j,(3,3))
<ipython-input-44-231d4427c425>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i , j : i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [45]:
[i*i for  i in range(5)]

[0, 1, 4, 9, 16]

In [46]:
(i*i for  i in range(5))

<generator object <genexpr> at 0x00000248CCE01AC0>

In [47]:
def test(x):
    yield x

In [48]:
test(5)

<generator object test at 0x00000248CCE0A200>

In [49]:
gen=(i*i for  i in range(5))

In [50]:
gen

<generator object <genexpr> at 0x00000248CCE01F90>

In [51]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [52]:
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [53]:
for i in gen:
    print(i)

In [54]:
np.fromstring('1,2,3,4,5',sep=',')

array([1., 2., 3., 4., 5.])

In [55]:
np.fromstring('1,2,3,4,5',sep=',',dtype=int)

array([1, 2, 3, 4, 5])

In [56]:
np.fromstring('45 2 6 8 4 55 11 2 3',sep=' ' , dtype=int)

array([45,  2,  6,  8,  4, 55, 11,  2,  3])

In [57]:
np.fromstring('45 2 6 8 4 55 11 2 3',sep=' ' , dtype=complex)

array([45.+0.j,  2.+0.j,  6.+0.j,  8.+0.j,  4.+0.j, 55.+0.j, 11.+0.j,
        2.+0.j,  3.+0.j])

In [58]:
l=[1,2,4,5,9,8]

In [59]:
arr=np.array(l)

In [60]:
arr1=np.array([[1,2,3,4],[2,5,6,8],[8,5,6,9]])
arr1

array([[1, 2, 3, 4],
       [2, 5, 6, 8],
       [8, 5, 6, 9]])

In [61]:
type(arr)

numpy.ndarray

In [62]:
arr1.ndim #check dimention

2

In [63]:
arr1.size #total no. of element

12

In [64]:
arr1.shape  # how many rows and columns

(3, 4)

In [65]:
arr1.dtype

dtype('int32')

In [66]:
arr.size

6

In [67]:
arr.ndim

1

In [68]:
arr.shape

(6,)

In [69]:
arr2=np.array([[[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]]])

In [70]:
arr2

array([[[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]]]])

In [71]:
arr2.size

16

In [72]:
arr.ndim

1

In [73]:
arr2.shape

(1, 2, 2, 4)

In [74]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [75]:
list(range(6.6)) # always take integer

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(6.6) # it accept floating point

In [ ]:
np.arange(6.6,9,0.3)  #6.6 to 9 with 0.3 jump

In [ ]:
 np.arange(9,6.6,-0.3)

In [ ]:
np.arange(1,9)

In [ ]:
np.linspace(1,9)

In [ ]:
np.linspace(1,2,5) # 1 or 5 kay darmyan 5 data generate

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((2,5))

In [ ]:
np.zeros((2,5,4)) # 2 matric of 4 * 5

In [ ]:
np.zeros((1,2,5,4)) 

In [ ]:
np.ones(4)

In [ ]:
np.ones((2,3))

In [ ]:
np.ones((2,3,1))

In [ ]:
np.ones((2,3,1)) + 5

In [ ]:
np.empty(5)

In [ ]:
np.empty((3,4))

In [ ]:
np.eye(3)

In [ ]:
np.linspace(2,4,4,endpoint=False,axis=0)

In [ ]:
np.linspace([1,6],4,endpoint=False,axis=0)

In [ ]:
np.linspace([1,6],4,endpoint=False,axis=1)

In [ ]:
np.logspace(2,3,5) 

In [ ]:
np.logspace([2,3],4) 

In [ ]:
np.logspace([2,3],4,axis=1) 

In [ ]:
np.logspace([2],[3],4,axis=1) 

In [ ]:
np.logspace([2],[3],4,axis=0) 

In [ ]:
d=np.linspace(4,7,40)

In [ ]:
d

In [ ]:
d.ndim

In [ ]:
d.shape

In [ ]:
d.reshape(40,1)

In [ ]:
d.reshape(2,1,20)

In [ ]:
d.reshape(1,2,1,20)

In [ ]:
d.reshape(1,4,10)

In [82]:
arr2=np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [83]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [84]:
arr2.size

16

In [85]:
arr2.ndim

3

In [86]:
arr2.shape # 2 numbers/dara of 2*4 data

(2, 2, 4)

In [88]:
arr3=np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7],]])
arr3

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [89]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [92]:
np.linspace(0.1,0.2,5)

array([0.1  , 0.125, 0.15 , 0.175, 0.2  ])

In [94]:
np.linspace(2,8) # by defaultgenerate 50 data set

array([2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
       2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
       3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
       3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
       4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551,
       5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
       5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
       6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
       6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
       7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ])

In [97]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [98]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [99]:
np.zeros((2,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [101]:
np.zeros((2,5,4,1)) # 4 * 1   5 such data  in 2 array

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [103]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [104]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [106]:
np.ones((3,4,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [108]:
np.linspace(5,2,8)

array([5.        , 4.57142857, 4.14285714, 3.71428571, 3.28571429,
       2.85714286, 2.42857143, 2.        ])

In [114]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [119]:
np.ones((2,3,1))/5

array([[[0.2],
        [0.2],
        [0.2]],

       [[0.2],
        [0.2],
        [0.2]]])

In [121]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [123]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [124]:
np.linspace(2,4,4) # end point is true. end point include

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [127]:
np.linspace(2,4,4,endpoint=False,axis=0)

array([2. , 2.5, 3. , 3.5])

In [128]:
np.linspace([1,4],4,endpoint=False,axis=0)

array([[1.  , 4.  ],
       [1.06, 4.  ],
       [1.12, 4.  ],
       [1.18, 4.  ],
       [1.24, 4.  ],
       [1.3 , 4.  ],
       [1.36, 4.  ],
       [1.42, 4.  ],
       [1.48, 4.  ],
       [1.54, 4.  ],
       [1.6 , 4.  ],
       [1.66, 4.  ],
       [1.72, 4.  ],
       [1.78, 4.  ],
       [1.84, 4.  ],
       [1.9 , 4.  ],
       [1.96, 4.  ],
       [2.02, 4.  ],
       [2.08, 4.  ],
       [2.14, 4.  ],
       [2.2 , 4.  ],
       [2.26, 4.  ],
       [2.32, 4.  ],
       [2.38, 4.  ],
       [2.44, 4.  ],
       [2.5 , 4.  ],
       [2.56, 4.  ],
       [2.62, 4.  ],
       [2.68, 4.  ],
       [2.74, 4.  ],
       [2.8 , 4.  ],
       [2.86, 4.  ],
       [2.92, 4.  ],
       [2.98, 4.  ],
       [3.04, 4.  ],
       [3.1 , 4.  ],
       [3.16, 4.  ],
       [3.22, 4.  ],
       [3.28, 4.  ],
       [3.34, 4.  ],
       [3.4 , 4.  ],
       [3.46, 4.  ],
       [3.52, 4.  ],
       [3.58, 4.  ],
       [3.64, 4.  ],
       [3.7 , 4.  ],
       [3.76, 4.  ],
       [3.82,

In [130]:
np.linspace([1,4],4,endpoint=False,axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  ]])

In [131]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [133]:
np.logspace([2,3],5)

array([[   100.        ,   1000.        ],
       [   115.13953993,   1098.54114199],
       [   132.57113656,   1206.79264064],
       [   152.64179672,   1325.71136559],
       [   175.75106249,   1456.3484775 ],
       [   202.35896477,   1599.85871961],
       [   232.99518105,   1757.51062485],
       [   268.26957953,   1930.69772888],
       [   308.88435965,   2120.95088792],
       [   355.64803062,   2329.95181052],
       [   409.49150624,   2559.5479227 ],
       [   471.48663635,   2811.76869797],
       [   542.86754393,   3088.84359648],
       [   625.05519253,   3393.2217719 ],
       [   719.685673  ,   3727.59372031],
       [   828.64277285,   4094.91506238],
       [   954.09547635,   4498.43266897],
       [  1098.54114199,   4941.71336132],
       [  1264.85521686,   5428.67543932],
       [  1456.3484775 ,   5963.62331659],
       [  1676.83293681,   6551.2855686 ],
       [  1930.69772888,   7196.85673001],
       [  2222.99648253,   7906.04321091],
       [  2

In [135]:
np.logspace([2,3],4,axis=1)

array([[  100.        ,   109.8541142 ,   120.67926406,   132.57113656,
          145.63484775,   159.98587196,   175.75106249,   193.06977289,
          212.09508879,   232.99518105,   255.95479227,   281.1768698 ,
          308.88435965,   339.32217719,   372.75937203,   409.49150624,
          449.8432669 ,   494.17133613,   542.86754393,   596.36233166,
          655.12855686,   719.685673  ,   790.60432109,   868.51137375,
          954.09547635,  1048.11313415,  1151.39539933,  1264.85521686,
         1389.49549437,  1526.41796718,  1676.83293681,  1842.06996933,
         2023.58964773,  2222.99648253,  2442.05309455,  2682.69579528,
         2947.05170255,  3237.45754282,  3556.48030622,  3906.93993705,
         4291.93426013,  4714.86636346,  5179.47467923,  5689.86602902,
         6250.55192527,  6866.48845004,  7543.12006335,  8286.42772855,
         9102.98177992, 10000.        ],
       [ 1000.        ,  1048.11313415,  1098.54114199,  1151.39539933,
         1206.79264064,

In [136]:
np.logspace([2],[3],axis=1)

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

In [137]:
np.logspace([2],[3],axis=0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [138]:
np.logspace([2,5],[3],axis=0) # start 2 and 5 , and end till 3 

array([[   100.        , 100000.        ],
       [   104.81131342,  91029.81779915],
       [   109.8541142 ,  82864.27728547],
       [   115.13953993,  75431.20063355],
       [   120.67926406,  68664.88450043],
       [   126.48552169,  62505.51925274],
       [   132.57113656,  56898.66029018],
       [   138.94954944,  51794.74679231],
       [   145.63484775,  47148.66363457],
       [   152.64179672,  42919.34260129],
       [   159.98587196,  39069.39937055],
       [   167.68329368,  35564.80306223],
       [   175.75106249,  32374.57542818],
       [   184.20699693,  29470.51702552],
       [   193.06977289,  26826.9579528 ],
       [   202.35896477,  24420.53094549],
       [   212.09508879,  22229.96482526],
       [   222.29964825,  20235.89647725],
       [   232.99518105,  18420.69969327],
       [   244.20530945,  16768.32936811],
       [   255.95479227,  15264.17967175],
       [   268.26957953,  13894.95494373],
       [   281.1768698 ,  12648.55216855],
       [   

In [140]:
d=np.linspace(4,7,40)

In [141]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [143]:
d.ndim

1

In [144]:
d.shape

(40,)

In [145]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [148]:
d.reshape(1,2,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [150]:
d.reshape(1,2,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [151]:
np.random.rand(3)

array([0.0897438 , 0.89606063, 0.12354396])

In [152]:
np.random.randn(5)

array([-1.69691193,  0.66112836, -0.95603559, -0.41623038, -0.43673961])

In [153]:
np.random.randn(5,4)

array([[ 1.65011314e+00, -4.61398471e-01,  2.08051929e-01,
        -1.45063911e+00],
       [-1.90053324e-01, -5.01297404e-01,  7.53143162e-01,
         1.50880220e+00],
       [-9.11353273e-01, -1.21098635e+00,  5.79040884e-01,
         3.65873704e-04],
       [ 1.01932474e+00, -1.24750018e-01,  2.90292287e-01,
        -2.48153905e-01],
       [ 1.58286389e+00,  1.25500687e+00, -2.56007367e-01,
        -1.66070221e+00]])

In [154]:
np.random.randn(2,3)

array([[ 0.21686978,  0.51830319,  0.29735388],
       [ 0.0127819 , -0.24768659,  1.11191081]])

In [155]:
np.random.randn(2,2,3)

array([[[ 0.29953755,  0.64817684,  0.0511841 ],
        [-0.07051095, -1.88297403, -0.00609441]],

       [[-1.73019644,  1.64563143, -0.49662019],
        [-1.1503453 ,  0.28436484,  0.65778437]]])

In [156]:
np.random.randint(5)

3

In [157]:
np.random.randint(5,60)

6

In [161]:
np.random.randint(5,60,(4,4)) # 4x4 btw 5,60

array([[ 5, 30, 24, 45],
       [ 8,  6, 35, 39],
       [14, 49, 33, 55],
       [50, 49, 18, 48]])

In [162]:
np.random.randn(5)

array([ 0.52728695, -0.77497531, -1.09892537,  1.02747876,  0.90326933])

In [163]:
arr=np.random.randint(3,9,(3,3))

In [164]:
arr

array([[7, 8, 8],
       [5, 4, 8],
       [7, 3, 3]])

In [166]:
arr.reshape(1,9)

array([[7, 8, 8, 5, 4, 8, 7, 3, 3]])

In [167]:
arr.reshape(9,1)

array([[7],
       [8],
       [8],
       [5],
       [4],
       [8],
       [7],
       [3],
       [3]])

In [170]:
arr.reshape(1,1,9)

array([[[7, 8, 8, 5, 4, 8, 7, 3, 3]]])

In [171]:
arr.reshape(3,3,1)

array([[[7],
        [8],
        [8]],

       [[5],
        [4],
        [8]],

       [[7],
        [3],
        [3]]])

In [172]:
arr.reshape(3,-1) # 3  and auto suggest remaining columns

array([[7, 8, 8],
       [5, 4, 8],
       [7, 3, 3]])

In [173]:
arr.reshape(1,-2) # put any -ve no. 

array([[7, 8, 8, 5, 4, 8, 7, 3, 3]])

In [174]:
arr.max()

8

In [176]:
arr.min()

3

In [179]:
arr=np.random.randint(4,10,(5,5))
arr

array([[9, 7, 4, 4, 4],
       [5, 9, 6, 4, 8],
       [4, 5, 7, 4, 5],
       [6, 8, 4, 8, 5],
       [7, 6, 4, 8, 6]])

In [181]:
arr[3:,3:]

array([[8, 5],
       [8, 6]])

In [182]:
arr[:,[1,3]]

array([[7, 4],
       [9, 4],
       [5, 4],
       [8, 8],
       [6, 8]])

In [183]:
arr>10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [186]:
arr[arr>7]

array([9, 9, 8, 8, 8, 8])

In [187]:
arr1=np.random.randint(2,4,(3,3))

In [190]:
arr2=np.random.randint(2,4,(3,3))

In [188]:
arr1

array([[3, 3, 2],
       [2, 3, 3],
       [3, 3, 2]])

In [191]:
arr2

array([[2, 2, 3],
       [2, 3, 2],
       [2, 2, 2]])

In [192]:
arr1*arr2

array([[4, 4, 6],
       [6, 9, 4],
       [4, 6, 6]])

In [193]:
arr1@arr2

array([[12, 14, 14],
       [16, 19, 19],
       [16, 19, 18]])

In [195]:
  arr**2

array([[81, 49, 16, 16, 16],
       [25, 81, 36, 16, 64],
       [16, 25, 49, 16, 25],
       [36, 64, 16, 64, 25],
       [49, 36, 16, 64, 36]], dtype=int32)

In [196]:
arr=np.zeros((3,4))

In [197]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [201]:
a=np.array([1,2,3,4])

In [202]:
a

array([1, 2, 3, 4])

In [203]:
arr+a

array([[[[1., 2., 3., 4.],
         [1., 2., 3., 4.],
         [1., 2., 3., 4.]],

        [[1., 2., 3., 4.],
         [1., 2., 3., 4.],
         [1., 2., 3., 4.]]]])

In [206]:
arr1=arr+5
arr1

array([[[[5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.]],

        [[5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.]]]])

In [207]:
np.sqrt(arr1)

array([[[[2.23606798, 2.23606798, 2.23606798, 2.23606798],
         [2.23606798, 2.23606798, 2.23606798, 2.23606798],
         [2.23606798, 2.23606798, 2.23606798, 2.23606798]],

        [[2.23606798, 2.23606798, 2.23606798, 2.23606798],
         [2.23606798, 2.23606798, 2.23606798, 2.23606798],
         [2.23606798, 2.23606798, 2.23606798, 2.23606798]]]])

In [208]:
np.log10(arr1)

array([[[[0.69897, 0.69897, 0.69897, 0.69897],
         [0.69897, 0.69897, 0.69897, 0.69897],
         [0.69897, 0.69897, 0.69897, 0.69897]],

        [[0.69897, 0.69897, 0.69897, 0.69897],
         [0.69897, 0.69897, 0.69897, 0.69897],
         [0.69897, 0.69897, 0.69897, 0.69897]]]])

In [209]:
np.exp(arr1)

array([[[[148.4131591, 148.4131591, 148.4131591, 148.4131591],
         [148.4131591, 148.4131591, 148.4131591, 148.4131591],
         [148.4131591, 148.4131591, 148.4131591, 148.4131591]],

        [[148.4131591, 148.4131591, 148.4131591, 148.4131591],
         [148.4131591, 148.4131591, 148.4131591, 148.4131591],
         [148.4131591, 148.4131591, 148.4131591, 148.4131591]]]])

In [2]:
np.log10(arr1)

NameError: name 'np' is not defined